In [1]:
import pandas as pd

orders = pd.read_csv("data/orders.csv")
orders.head()

,order_id,customer_id,order_date,market,category,channel,customer_segment,qty,unit_price_local,fx_to_cny,...,coupon_given,coupon_value_cny,gift_given,gift_cost_cny,sentiment_score,complaint_flag,refund_flag,refund_amount_cny,profit_cny,margin_pct
0,1,10354,2024-02-02,KR,Sneakers,TikTok,Student,3,171585.25,0.0053,...,0,0,0,0,4.0,0,0,0.0,202.35,0.0628
1,2,10046,2024-10-10,US,Streetwear,WeChat,Student,2,70.94,7.0912,...,0,0,0,0,3.8,0,0,0.0,122.25,0.0978
2,3,10175,2024-08-27,TH,Outerwear,Referral,ValueSeeker,3,1656.60,0.2004,...,1,10,0,0,4.1,0,0,0.0,-50.92,-0.0437
3,4,10707,2024-06-09,KR,Basics,Referral,Student,3,66922.09,0.0053,...,1,30,0,0,4.7,0,0,0.0,-37.70,-0.0320
4,5,10109,2024-06-07,CA,Accessories,Instagram,Student,1,40.17,5.2843,...,0,0,0,0,4.6,0,0,0.0,-9.93,-0.0397

In [2]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 30 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   order_id           3500 non-null   int64
 1   customer_id        3500 non-null   int64
 2   order_date         3500 non-null   str
 3   market             3500 non-null   str
 4   category           3500 non-null   str
 5   channel            3500 non-null   str
 6   customer_segment   3500 non-null   str
 7   qty                3500 non-null   int64
 8   unit_price_local   3500 non-null   float64
 9   fx_to_cny          3500 non-null   float64
 10  cogs_cny           3500 non-null   float64
 11  sell_price_cny     3500 non-null   float64
 12  warehouse_type     3500 non-null   str
 13  warehouse_fee_cny  3500 non-null   float64
 14  shipping_mode      3500 non-null   str
 15  shipping_cost_cny  3500 non-null   float64
 16  weight_kg          3500 non-null   float64
 17  expected_days      3500 non-null   int64
 18  delay_days         3500 non-null   int64
 19  actual_days        3500 non-null   int64
 20  coupon_given       3500 non-null   int64
 21  coupon_value_cny   3500 non-null   int64
 22  gift_given         3500 non-null   int64
 23  gift_cost_cny      3500 non-null   int64
 24  sentiment_score    3500 non-null   float64
 25  complaint_flag     3500 non-null   int64
 26  refund_flag        3500 non-null   int64
 27  refund_amount_cny  3500 non-null   float64
 28  profit_cny         3500 non-null   float64
 29  margin_pct         3500 non-null   float64
dtypes: float64(11), int64(12), str(7)
memory usage: 820.4 KB

In [3]:
orders.isna().sum().sort_values(ascending=False)

order_id             0
customer_id          0
profit_cny           0
refund_amount_cny    0
refund_flag          0
complaint_flag       0
sentiment_score      0
gift_cost_cny        0
gift_given           0
coupon_value_cny     0
coupon_given         0
actual_days          0
delay_days           0
expected_days        0
weight_kg            0
shipping_cost_cny    0
shipping_mode        0
warehouse_fee_cny    0
warehouse_type       0
sell_price_cny       0
cogs_cny             0
fx_to_cny            0
unit_price_local     0
qty                  0
customer_segment     0
channel              0
category             0
market               0
order_date           0
margin_pct           0
dtype: int64

In [4]:
orders[[
    "sell_price_cny",
    "profit_cny",
    "margin_pct",
    "delay_days",
    "sentiment_score"
]].describe()

       sell_price_cny   profit_cny   margin_pct   delay_days  sentiment_score
count     3500.000000  3500.000000  3500.000000  3500.000000      3500.000000
mean      1235.512943    59.699569     0.007204     1.278571         4.347629
std        916.484151   156.261480     0.119835     3.705869         0.403156
min         62.130000 -2822.370000    -1.164000     0.000000         2.500000
25%        568.917500   -15.667500    -0.028000     0.000000         4.100000
50%        969.750000    29.900000     0.033000     0.000000         4.400000
75%       1646.282500   108.887500     0.075225     0.000000         4.600000
max       6198.010000  1092.480000     0.194600    17.000000         5.000000

In [3]:
import pandas as pd

orders = pd.read_csv("data/orders.csv")
orders.head()

,order_id,customer_id,order_date,market,category,channel,customer_segment,qty,unit_price_local,fx_to_cny,...,coupon_given,coupon_value_cny,gift_given,gift_cost_cny,sentiment_score,complaint_flag,refund_flag,refund_amount_cny,profit_cny,margin_pct
0,1,10354,2024-02-02,KR,Sneakers,TikTok,Student,3,171585.25,0.0053,...,0,0,0,0,4.0,0,0,0.0,202.35,0.0628
1,2,10046,2024-10-10,US,Streetwear,WeChat,Student,2,70.94,7.0912,...,0,0,0,0,3.8,0,0,0.0,122.25,0.0978
2,3,10175,2024-08-27,TH,Outerwear,Referral,ValueSeeker,3,1656.60,0.2004,...,1,10,0,0,4.1,0,0,0.0,-50.92,-0.0437
3,4,10707,2024-06-09,KR,Basics,Referral,Student,3,66922.09,0.0053,...,1,30,0,0,4.7,0,0,0.0,-37.70,-0.0320
4,5,10109,2024-06-07,CA,Accessories,Instagram,Student,1,40.17,5.2843,...,0,0,0,0,4.6,0,0,0.0,-9.93,-0.0397

In [4]:
import pandas as pd

kpi = pd.Series({
    "Total Orders": len(orders),
    "Unique Customers": orders["customer_id"].nunique(),
    "Total Revenue (CNY)": orders["sell_price_cny"].sum(),
    "Total Profit (CNY)": orders["profit_cny"].sum(),
    "Avg Margin %": orders["margin_pct"].mean(),
    "On-time Rate": (orders["delay_days"] == 0).mean(),
    "Avg Delivery Days": orders["actual_days"].mean(),
    "Complaint Rate": orders["complaint_flag"].mean(),
    "Refund Rate": orders["refund_flag"].mean(),
    "Avg Sentiment (1-5)": orders["sentiment_score"].mean(),
})

kpi.to_frame("value")

                            value
Total Orders         3.500000e+03
Unique Customers     8.840000e+02
Total Revenue (CNY)  4.324295e+06
Total Profit (CNY)   2.089485e+05
Avg Margin %         7.203600e-03
On-time Rate         8.694286e-01
Avg Delivery Days    1.592486e+01
Complaint Rate       3.171429e-02
Refund Rate          9.142857e-03
Avg Sentiment (1-5)  4.347629e+00

In [5]:
kpi_round = kpi.copy()

kpi_round["Total Revenue (CNY)"] = round(kpi_round["Total Revenue (CNY)"], 0)
kpi_round["Total Profit (CNY)"] = round(kpi_round["Total Profit (CNY)"], 0)
kpi_round["Avg Margin %"] = round(kpi_round["Avg Margin %"] * 100, 2)
kpi_round["On-time Rate"] = round(kpi_round["On-time Rate"] * 100, 2)
kpi_round["Complaint Rate"] = round(kpi_round["Complaint Rate"] * 100, 2)
kpi_round["Refund Rate"] = round(kpi_round["Refund Rate"] * 100, 2)

kpi_round.to_frame("value")

                            value
Total Orders         3.500000e+03
Unique Customers     8.840000e+02
Total Revenue (CNY)  4.324295e+06
Total Profit (CNY)   2.089480e+05
Avg Margin %         7.200000e-01
On-time Rate         8.694000e+01
Avg Delivery Days    1.592486e+01
Complaint Rate       3.170000e+00
Refund Rate          9.100000e-01
Avg Sentiment (1-5)  4.347629e+00

In [6]:
market_analysis = orders.groupby("market").agg(
    orders=("order_id", "count"),
    revenue=("sell_price_cny", "sum"),
    profit=("profit_cny", "sum"),
    avg_margin=("margin_pct", "mean"),
    avg_delay=("delay_days", "mean"),
    refund_rate=("refund_flag", "mean")
).sort_values("profit", ascending=False)

market_analysis

        orders     revenue     profit  avg_margin  avg_delay  refund_rate
market
US        1218  1757775.65  101558.19    0.020726   1.386700     0.010673
KR         662   820872.67   55646.14    0.035801   1.051360     0.007553
TH         560   630716.74   38239.76    0.026500   1.444643     0.010714
CA         545   562276.80   12246.21   -0.017489   1.155963     0.003670
AU         515   552653.44    1258.19   -0.056388   1.264078     0.011650

In [7]:
shipping_analysis = orders.groupby("shipping_mode").agg(
    orders=("order_id", "count"),
    avg_delay=("delay_days", "mean"),
    avg_margin=("margin_pct", "mean"),
    refund_rate=("refund_flag", "mean"),
    avg_shipping_cost=("shipping_cost_cny", "mean")
).sort_values("avg_margin")

shipping_analysis

               orders  avg_delay  avg_margin  refund_rate  avg_shipping_cost
shipping_mode
Express           472   0.442797   -0.037600     0.006356         161.748347
Standard         1459   1.228924    0.001601     0.008225         122.800384
Economy          1569   1.576163    0.025891     0.010835          99.735551

In [8]:
markets_focus = ["AU", "CA", "US", "KR", "TH"]

cost_breakdown = orders[orders["market"].isin(markets_focus)].groupby("market").agg(
    orders=("order_id", "count"),
    revenue=("sell_price_cny", "mean"),
    cogs=("cogs_cny", "mean"),
    ship=("shipping_cost_cny", "mean"),
    wh=("warehouse_fee_cny", "mean"),
    voucher=("coupon_value_cny", "mean"),
    gift=("gift_cost_cny", "mean"),
    refund=("refund_amount_cny", "mean"),
    profit=("profit_cny", "mean"),
    margin=("margin_pct", "mean"),
).round(2)

cost_breakdown

,orders,revenue,cogs,ship,wh,voucher,gift,refund,profit,margin
market,,,,,,,,,,
AU,515,1073.11,898.36,144.57,13.09,4.77,0.91,8.97,2.44,-0.06
CA,545,1031.70,863.37,121.05,12.39,4.49,1.00,6.94,22.47,-0.02
KR,662,1239.99,1038.45,96.60,11.86,5.54,1.17,2.32,84.06,0.04
TH,560,1126.28,938.66,93.20,12.70,4.34,1.12,7.98,68.29,0.03
US,1218,1443.17,1206.26,127.61,12.31,4.78,1.16,7.68,83.38,0.02

In [9]:
pd.crosstab(
    orders["market"],
    orders["shipping_mode"],
    normalize="index"
).loc[["AU","CA","US","KR","TH"]].round(3)

shipping_mode  Economy  Express  Standard
market
AU               0.441    0.146     0.414
CA               0.479    0.114     0.407
US               0.446    0.132     0.422
KR               0.450    0.147     0.403
TH               0.429    0.138     0.434

In [10]:
lane_ship = orders.groupby(["market","shipping_mode"]).agg(
    orders=("order_id","count"),
    avg_ship=("shipping_cost_cny","mean"),
    avg_profit=("profit_cny","mean"),
    avg_margin=("margin_pct","mean"),
    avg_delay=("delay_days","mean")
).reset_index()

lane_ship[lane_ship["market"].isin(["AU","CA","US","KR","TH"])].sort_values(["shipping_mode","avg_ship"], ascending=[True, False]).head(15)

   market shipping_mode  orders    avg_ship  avg_profit  avg_margin  avg_delay
0      AU       Economy     227  121.146123   21.041542   -0.027522   1.753304
12     US       Economy     543  109.385157  106.052210    0.039245   1.744015
3      CA       Economy     261  102.758123   35.500498    0.006003   1.390805
6      KR       Economy     298   80.225638   94.971946    0.048373   1.218121
9      TH       Economy     240   78.590250   77.755750    0.039910   1.675000
1      AU       Express      75  207.576000  -58.779200   -0.131868   0.200000
4      CA       Express      62  169.814032  -12.297903   -0.073490   0.564516
13     US       Express     161  168.488882   23.661739   -0.019176   0.273292
7      KR       Express      97  134.289794   52.434433   -0.003435   0.855670
10     TH       Express      77  131.113377   43.682597    0.001558   0.415584
2      AU      Standard     213  147.348779    4.179343   -0.060574   1.117371
14     US      Standard     514  134.057879   78.136770    0.013659   1.357977
5      CA      Standard     222  128.944865   16.860586   -0.029468   1.045045
8      KR      Standard     267  101.177753   83.364644    0.036024   0.936330
11     TH      Standard     243   95.615226   66.727654    0.021158   1.543210

In [11]:
au_wh = orders[orders["market"]=="AU"].groupby("warehouse_type").agg(
    orders=("order_id","count"),
    avg_ship=("shipping_cost_cny","mean"),
    avg_wh=("warehouse_fee_cny","mean"),
    avg_profit=("profit_cny","mean"),
    avg_margin=("margin_pct","mean"),
    avg_delay=("delay_days","mean")
).sort_values("avg_margin")

au_wh

,orders,avg_ship,avg_wh,avg_profit,avg_margin,avg_delay
warehouse_type,,,,,,
3PL_Standard,169,144.014675,13.961183,-12.047811,-0.068149,1.325444
BrandWarehouse,81,141.822840,17.058148,6.795432,-0.058668,0.913580
3PL_Budget,137,153.572190,10.982920,14.545547,-0.049032,1.452555
Forwarder_Aggregator,128,137.407344,11.674375,5.867969,-0.047291,1.203125

In [13]:
price_gap = orders.groupby("market").agg(
    avg_price=("sell_price_cny","mean"),
    avg_cost=("cogs_cny","mean"),
    avg_ship=("shipping_cost_cny","mean"),
    avg_profit=("profit_cny","mean"),
    avg_margin=("margin_pct","mean")
).round(2)

price_gap

        avg_price  avg_cost  avg_ship  avg_profit  avg_margin
market
AU        1073.11    898.36    144.57        2.44       -0.06
CA        1031.70    863.37    121.05       22.47       -0.02
KR        1239.99   1038.45     96.60       84.06        0.04
TH        1126.28    938.66     93.20       68.29        0.03
US        1443.17   1206.26    127.61       83.38        0.02

In [14]:
delay_financial = orders.groupby("delay_bucket").agg(
    orders=("order_id","count"),
    avg_delay=("delay_days","mean"),
    refund_rate=("refund_flag","mean"),
    avg_profit=("profit_cny","mean"),
    avg_margin=("margin_pct","mean")
)

delay_financial

KeyError: 'delay_bucket'

In [15]:
import pandas as pd

bins = [-1, 0, 3, 7, 14, 1000]
labels = ["On time", "1-3 days", "4-7 days", "8-14 days", "15+ days"]

orders["delay_bucket"] = pd.cut(
    orders["delay_days"],
    bins=bins,
    labels=labels
)

orders[["delay_days", "delay_bucket"]].head()

   delay_days delay_bucket
0           0      On time
1           0      On time
2           0      On time
3           0      On time
4           0      On time

In [16]:
delay_summary = orders.groupby("delay_bucket").agg(
    orders=("order_id","count"),
    avg_delay=("delay_days","mean"),
    avg_sentiment=("sentiment_score","mean"),
    complaint_rate=("complaint_flag","mean"),
    refund_rate=("refund_flag","mean"),
    avg_profit=("profit_cny","mean"),
    avg_margin=("margin_pct","mean")
).round(4)

delay_summary

,orders,avg_delay,avg_sentiment,complaint_rate,refund_rate,avg_profit,avg_margin
delay_bucket,,,,,,,
On time,3043,0.0000,4.4257,0.0299,0.0079,61.5706,0.0074
1-3 days,50,2.5400,4.1820,0.0000,0.0200,20.8518,-0.0122
4-7 days,119,5.5798,4.0597,0.0168,0.0000,56.1915,0.0219
8-14 days,181,10.9171,3.7762,0.0663,0.0110,54.7302,0.0132
15+ days,107,15.9626,3.4916,0.0561,0.0467,36.9485,-0.0148

In [17]:
extreme_delay = orders[orders["delay_bucket"]=="15+ days"]

extreme_lane = extreme_delay.groupby(["market","shipping_mode"]).agg(
    orders=("order_id","count"),
    avg_delay=("delay_days","mean"),
    refund_rate=("refund_flag","mean"),
    avg_margin=("margin_pct","mean")
).reset_index().sort_values("orders", ascending=False)

extreme_lane.head(10)

   market shipping_mode  orders  avg_delay  refund_rate  avg_margin
12     US      Standard      21  16.285714     0.047619   -0.038252
10     US       Economy      19  15.894737     0.052632    0.002905
9      TH      Standard      11  16.000000     0.000000    0.012773
4      KR       Economy      10  16.100000     0.000000    0.036870
0      AU       Economy       9  15.777778     0.000000    0.001411
7      TH       Economy       9  15.888889     0.111111    0.027256
3      CA      Standard       8  15.750000     0.125000   -0.096925
2      CA       Economy       7  15.428571     0.000000    0.001914
1      AU      Standard       6  16.500000     0.166667   -0.180767
6      KR      Standard       4  15.250000     0.000000    0.043200

In [18]:
extreme = orders[orders["delay_bucket"] == "15+ days"]

extreme_voucher = extreme.groupby("coupon_given").agg(
    orders=("order_id","count"),
    avg_sentiment=("sentiment_score","mean"),
    complaint_rate=("complaint_flag","mean"),
    refund_rate=("refund_flag","mean"),
    avg_profit=("profit_cny","mean"),
    avg_margin=("margin_pct","mean")
).round(4)

extreme_voucher

,orders,avg_sentiment,complaint_rate,refund_rate,avg_profit,avg_margin
coupon_given,,,,,,
0,75,3.5253,0.08,0.0533,44.4125,-0.0097
1,32,3.4125,0.00,0.0312,19.4547,-0.0265

In [19]:
bucket_coupon = orders.groupby(["delay_bucket","coupon_given"]).agg(
    orders=("order_id","count"),
    avg_sentiment=("sentiment_score","mean"),
    refund_rate=("refund_flag","mean"),
    avg_profit=("profit_cny","mean"),
    avg_margin=("margin_pct","mean")
).round(4)

bucket_coupon

                           orders  avg_sentiment  refund_rate  avg_profit  \
delay_bucket coupon_given
On time      0               2356         4.4176       0.0081     69.0185
             1                687         4.4536       0.0073     36.0289
1-3 days     0                 36         4.1889       0.0278     15.1031
             1                 14         4.1643       0.0000     35.6343
4-7 days     0                 91         4.0604       0.0000     61.8976
             1                 28         4.0571       0.0000     37.6468
8-14 days    0                136         3.7522       0.0074     64.2014
             1                 45         3.8489       0.0222     26.1062
15+ days     0                 75         3.5253       0.0533     44.4125
             1                 32         3.4125       0.0312     19.4547

                           avg_margin
delay_bucket coupon_given
On time      0                 0.0156
             1                -0.0208
1-3 days     0                -0.0080
             1                -0.0231
4-7 days     0                 0.0277
             1                 0.0031
8-14 days    0                 0.0198
             1                -0.0066
15+ days     0                -0.0097
             1                -0.0265

In [20]:

lane = orders[
    (orders["market"]=="US") &
    (orders["shipping_mode"]=="Standard")
].copy()

original_margin = lane["margin_pct"].mean()

lane["sim_ship_cost"] = lane["shipping_cost_cny"] * 1.15

lane["sim_refund_amount"] = lane["refund_amount_cny"]

mask_extreme = lane["delay_bucket"]=="15+ days"
lane.loc[mask_extreme, "sim_refund_amount"] *= 0.6

lane["sim_profit"] = lane["sell_price_cny"] - (
    lane["cogs_cny"] +
    lane["sim_ship_cost"] +
    lane["warehouse_fee_cny"] +
    lane["coupon_value_cny"] +
    lane["gift_cost_cny"] +
    lane["sim_refund_amount"]
)

lane["sim_margin"] = lane["sim_profit"] / lane["sell_price_cny"]

simulated_margin = lane["sim_margin"].mean()

original_margin, simulated_margin

(np.float64(0.013659338521400778), np.float64(-0.003816205957365718))

In [21]:
import numpy as np

lane = orders[(orders["market"]=="US") & (orders["shipping_mode"]=="Standard")].copy()

# 原始平均margin
base_margin = lane["margin_pct"].mean()

# 升级后：运费 +15%
ship_up = lane["shipping_cost_cny"] * 1.15

# 其他成本不变
other_cost = (
    lane["cogs_cny"] +
    lane["warehouse_fee_cny"] +
    lane["warehouse_fee_cny"]*0 +  # 占位，不影响
    lane["coupon_value_cny"] +
    lane["gift_cost_cny"]
)

# 原始退款金额
refund_base = lane["refund_amount_cny"].copy()

# 只对 15+ days 的退款金额做缩放：乘 (1 - r)
mask_extreme = lane["delay_bucket"] == "15+ days"

def sim_margin(r):
    refund_sim = refund_base.copy()
    refund_sim.loc[mask_extreme] = refund_sim.loc[mask_extreme] * (1 - r)
    profit_sim = lane["sell_price_cny"] - (other_cost + ship_up + refund_sim)
    return (profit_sim / lane["sell_price_cny"]).mean()

# 扫描 r=0%..100%
rs = np.linspace(0, 1, 21)
sim_margins = [sim_margin(r) for r in rs]

# 找到 break-even：模拟margin >= 原始margin 的最小r
breakeven = None
for r, m in zip(rs, sim_margins):
    if m >= base_margin:
        breakeven = r
        break

base_margin, breakeven, list(zip(rs, sim_margins))[:5]

(np.float64(0.013659338521400778),
 None,
 [(np.float64(0.0), np.float64(-0.00447586877524054)),
  (np.float64(0.05), np.float64(-0.0043934109230061875)),
  (np.float64(0.1), np.float64(-0.004310953070771835)),
  (np.float64(0.15000000000000002), np.float64(-0.004228495218537482)),
  (np.float64(0.2), np.float64(-0.0041460373663031284))])

In [22]:
import numpy as np

lane = orders[(orders["market"]=="AU") & (orders["shipping_mode"]=="Standard")].copy()

base_margin = lane["margin_pct"].mean()
ship_up = lane["shipping_cost_cny"] * 1.15

other_cost = (
    lane["cogs_cny"] +
    lane["warehouse_fee_cny"] +
    lane["coupon_value_cny"] +
    lane["gift_cost_cny"]
)

refund_base = lane["refund_amount_cny"].copy()
mask_extreme = lane["delay_bucket"] == "15+ days"

def sim_margin(r):
    refund_sim = refund_base.copy()
    refund_sim.loc[mask_extreme] = refund_sim.loc[mask_extreme] * (1 - r)
    profit_sim = lane["sell_price_cny"] - (other_cost + ship_up + refund_sim)
    return (profit_sim / lane["sell_price_cny"]).mean()

rs = np.linspace(0, 1, 21)
sim_margins = [sim_margin(r) for r in rs]

breakeven = None
for r, m in zip(rs, sim_margins):
    if m >= base_margin:
        breakeven = r
        break

base_margin, breakeven, list(zip(rs, sim_margins))[:5]

(np.float64(-0.06057417840375587),
 None,
 [(np.float64(0.0), np.float64(-0.08822562402977663)),
  (np.float64(0.05), np.float64(-0.08805149154408311)),
  (np.float64(0.1), np.float64(-0.08787735905838957)),
  (np.float64(0.15000000000000002), np.float64(-0.08770322657269604)),
  (np.float64(0.2), np.float64(-0.08752909408700252))])

In [23]:
au_std = orders[(orders["market"]=="AU") & (orders["shipping_mode"]=="Standard")].copy()

au_std[["cogs_cny","shipping_cost_cny","refund_amount_cny","profit_cny"]].mean()

cogs_cny             890.651690
shipping_cost_cny    147.348779
refund_amount_cny      2.293146
profit_cny             4.179343
dtype: float64

In [24]:
profit_bridge = orders[[
    "sell_price_cny",
    "cogs_cny",
    "shipping_cost_cny",
    "warehouse_fee_cny",
    "coupon_value_cny",
    "gift_cost_cny",
    "refund_amount_cny",
    "profit_cny"
]].mean()

profit_bridge

sell_price_cny       1235.512943
cogs_cny             1033.002057
shipping_cost_cny     117.713160
warehouse_fee_cny      12.410806
coupon_value_cny        4.805714
gift_cost_cny           1.091714
refund_amount_cny       6.789923
profit_cny             59.699569
dtype: float64

In [25]:
avg_price = orders["sell_price_cny"].mean()

profit_ratio = {
    "COGS_ratio": profit_bridge["cogs_cny"] / avg_price,
    "Shipping_ratio": profit_bridge["shipping_cost_cny"] / avg_price,
    "Warehouse_ratio": profit_bridge["warehouse_fee_cny"] / avg_price,
    "Coupon_ratio": profit_bridge["coupon_value_cny"] / avg_price,
    "Gift_ratio": profit_bridge["gift_cost_cny"] / avg_price,
    "Refund_ratio": profit_bridge["refund_amount_cny"] / avg_price,
    "Profit_ratio": profit_bridge["profit_cny"] / avg_price
}

profit_ratio

{'COGS_ratio': np.float64(0.8360916517426549),
 'Shipping_ratio': np.float64(0.09527472834706731),
 'Warehouse_ratio': np.float64(0.01004506329620921),
 'Coupon_ratio': np.float64(0.003889651106852022),
 'Gift_ratio': np.float64(0.000883612180694505),
 'Refund_ratio': np.float64(0.005495630698486293),
 'Profit_ratio': np.float64(0.04831966262803559)}